package liberr.net.airbclient.model

data class Listing(
        val id: Int,
        val name: String,
        val personCapacity: Int,
        val bathrooms: Int,
        val bedrooms: Int,
        val beds: Int,
        val city: String,
        val coworkerHosted: Boolean,
        val distance: Any,
        val instantBookable: Boolean,
        val isBusinessTravelReady: Boolean,
        val isNewListing: Boolean,
        val lat: Double,
        val lng: Double,
        val listingTags: List<Any>,
        val neighborhood: String,
        val pictureUrl: String,
        val propertyType: String,
        val propertyTypeId: Int,
        val publicAddress: String,
        val reviewsCount: Int,
        val roomType: String,
        val roomTypeCategory: String,
        val scrimColor: String,
        val starRating: Int,
        val thumbnailUrl: String,
        val user: User,
        val userId: Int,
        val xlPictureUrl: String,
        val previewEncodedPng: String,
        val pictureUrls: List<String>,
        val xlPictureUrls: List<String>
)
